apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: mi-api-alert-config
  namespace: monitoring # Importante: Debe ir en el namespace donde corre tu Prometheus/Alertmanager
spec:
  route:
    groupBy: ['alertname', 'job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'telegram-chatbot'
    continue: false
  receivers:
  - name: 'telegram-chatbot'
    telegramConfigs:
    - botToken:
        name: telegram-bot-secret  # Nombre del Secret de Kubernetes
        key: token                  # Clave dentro del Secret
      chatId: 1943944263           # ID de tu chat o canal (recuerda mantener el signo menos si aplica)
      sendResolved: true