apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: api-traffic-alerts
  namespace: monitoring
  labels:
    release: grafana-stack
    app: kube-prometheus-stack
    prometheus: k8s
spec:
  groups:
  - name: api-rules
    rules:
    - alert: ApiServerHighTraffic
      expr: suma(rate(apiserver_requests_total[1m])) > 3
      for: 10s
      labels:
        severity: critical
      annotations:
        summary: "¡Alerta Crítica! Alto tráfico detectado en el API Server"
        description: "El API Server esta recibiendo mas de 3 peticiones por segundo."
